
-- Table: SYS_Seccion
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (1, 'UPM', 'Información general del conglomerado', 'informacionGeneralUPM', '0', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (2, 'UPM', 'Referencia de ubicación al punto de control', 'puntoControlUPM', '0', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (3, 'UPM', 'Características de inaccesibilidad al conglomerado', 'inaccesibleUPM', '0', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (4, 'Sitio', 'Ubicacion del sitio de muestreo', 'ubicacionSitio', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (7, 'Sitio', 'cobertura del suelo', 'coberturaSuelo', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (8, 'Taxonomia', 'Registro de sotobosque', 'sotoBosque', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (9, 'Taxonomia', 'Registro de repoblado', 'repoblado', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (10, 'Taxonomia', 'Arbolado', 'arbolado', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (11, 'Taxonomia', 'Arbolado de la submuestra', 'submuestra', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (12, 'Sitio', 'Clave de la vegetación', 'claveVegetacion', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (13, 'UPM', 'Características de la UPM', 'caracteristicasUPM', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (14, 'Carbono e incendios', 'Material leñoso caído 1, 10 y 100 horas', 'carbonoIncendios', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (15, 'Carbono e incendios', 'Material leñoso caído 1,000 horas', '', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (16, 'Carbono e incendios', 'Altura de arbustos, hierbas y pasto', '', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (17, 'Taxonomia', 'Longitud interceptada por componente', 'longitudInterceptada', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (18, 'Carbono e incendios', 'Cobertura dosel', '', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (19, 'Suelo', 'Información de suelo', 'suelo', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (20, 'Suelo', 'Evaluacion de las condiciones de degradacion del suelo', 'condicionDegradacion', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (21, 'Suelo', 'Erosion hidrica por deformacion del terrreno', 'erosionHidrica', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (22, 'Suelo', 'Deformacion del terreno por accion del viento', 'deformacionTerreno', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (23, 'Sitio', 'Observaciones', 'observaciones', 'A', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (24, 'Taxonomia', 'Arbolado', 'arboladoD', 'D', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (25, 'Suelo', 'Hojarasca y profundidad de suelo', 'hojarascaProfundidad', 'E', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (26, 'Suelo', 'Muestras del perfil', 'muestrasPerfil', 'E', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (27, 'Sitio', 'Toma de fotografia hemisferica', 'fotografiaHemisferica', 'F', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (28, 'Sitio', 'Parametros fisico quimicos', 'parametrosFQ', 'G', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (29, 'Taxonomia', 'Registro de repoblado vegetacion menor', 'repobladoVM', 'G', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (30, 'Taxonomia', 'Arbolado', 'arboladoG', 'G', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (31, 'Taxonomia', 'Vegetacion Menor', 'vegetacionMenor', 'H', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (32, 'Taxonomia', 'Vegetacion Mayor morfotipos creciendo de manera individual', 'vegetacionMayorI', 'H', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (33, 'TaxonomiA', 'Vegetacion Mayor morfotipos creciendo de manera gregaria', 'vegetacionMayorG', 'H', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (44, 'Suelo', 'Muestreo de densidad aparente', NULL, 'E', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (45, 'Suelo', 'Muestras del perfil', NULL, 'E', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (46, 'Sitio', 'Toma de fotografía hemisférica', NULL, 'F', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (47, 'Parámetros físico-químicos', 'Agua superficial-intersticial', NULL, 'G', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (48, 'Sitio', 'Registro de vegetación menor y cobertura del suelo', NULL, 'G', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (49, 'Taxonomia', 'Registro de repoblado y vegetación menor', NULL, 'G', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (50, 'Taxonomia', 'Arbolado', NULL, 'G', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (51, 'Taxonomia', 'Vegetación menor', NULL, 'H', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (53, 'Taxonomia', 'Vegetacion Mayor MCMG', NULL, 'H', NULL);
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (52, 'Taxonomia', 'Vegetacion Mayor MCMI', NULL, 'H', NULL);
